# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

- task: UnityGetProjectVersionTask@1
  name: UnityProjectVersion
  displayName: 'Unity Get Project Version'
  inputs:

trigger:
- master

pool:
  name: 'Windows Latest VM'
  vmImage: 'windows-latest'

steps:
- script: echo This project is using Unity version $(UnityProjectVersion.projectVersion)
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
